#-------------------------------
# General Site Settings
baseURL = "http://example.org/"
languageCode = "en-us"
title = "Prolog"
googleAnalytics = "" # Add your identifier. For example UA-99631805-1.
paginate = 12


#-------------------------------
# Main Menu
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Latest"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    name = "Pages"
    weight = 4
    hasChildren = true

  [[menu.main]]
    parent = "Pages"
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    parent = "Pages"
    name = "Contact"
    url = "/contact/"
    weight = 2

  [[menu.main]]
    parent = "Pages"
    name = "Videos"
    url = "/videos/"
    weight = 3

  [[menu.main]]
    parent = "Pages"
    name = "Featured"
    url = "/featured/"
    weight = 4

  # Call to action button
  [params.cta_button]
    enable = true
    cta_button_link = "/contact/"
    cta_button_text = "Get in touch"


[params]
  logo = "/images/logo.png" # You can add own logo. For example "/images/logo.png".
  logo_dark = "/images/logo-dark.png"
  description = "The only constant in tech industry is change"
  color_scheme = "auto" # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


  #-------------------------------
  # Hero Settings
  [params.hero]
    enable = true
    hero__title = "The only constant in tech industry is change"
    hero__description = "I share my thoughts, ideas, feelings and experience on all things I'm passionate about especially related to technology and computer programming"


  #-------------------------------
  # Tags Section Settings
  [params.tags_section]
    enable = true
    number_posts = 3 # To control how many posts to show under each tag section, set the value to a number. Three is the default.
    number_columns = 3 # You can specify the number of columns from 1-4 for large screen resolution. By default, the theme uses three columns grid.

  [[params.tag]]
    tag = "Blazor"

  [[params.tag]]
    tag = "DotNet"

  [[params.tag]]
    tag = "GitHub"

  # You can add many tag sections to the homepage; each section will show the recent posts by the tag.


  #-------------------------------
  # Authors Section Settings
  [params.authors_section]
    enable = true
    section_title = "About me"
    section_description = "I have been working as a programmer since 1996. I do this for a living and love what I do as every day there is something new and exciting to learn."

  #-------------------------------
  # Footer Settings
  [params.footer]
    footer__description = ""

  # Social Links
  [[params.social]]
    icon = "ion-logo-twitter"
    name = "Twitter"
    link = "https://twitter.com/thierry_langie"

  [[params.social]]
    icon = "ion-logo-facebook"
    name = "Facebook"
    link = "https://facebook.com/thierry.langie"

  [[params.social]]
    icon = "ion-logo-github"
    name = "Github"
    link = "https://github.com/Bronzato1"

  # Example of adding a new link to the footer section:
  # [[params.social]]
  #   icon = "ion-logo-vimeo"
  #   name = "Vimeo"
  #   link = "https://vimeo.com"

  # Other icons can be found at https://ionicons.com/v4/



  # Newsletter
  [params.mailchimp]
    enable = true
    mailchimp__title = "Get interesting news"
    mailchimp__description = "Subscribe to my newsletter and I’ll send you the emails of latest posts."
    mailchimp__identifier = "skynet.us14.list-manage.com/subscribe/post?u=ac4365a7c821c0a59702c9c8d&amp;id=39595d208d&amp;f_id=00a586e0f0" 
    # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
    mailchimp__input__text = "Your email address"
    mailchimp__button__text = "Subscribe"


  #-------------------------------
  # Contact Settings
  [params.contact]
    email = "xrgwbowo" # Add your form_id

    # NOTE
    # Danto comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.

  #-------------------------------
  # Comment Section (Disqus)
  [params.disqus]
    enable = true
    disqusShortname = "anvod-studio-test" # Add your shortname for Disqus Comment. For example anvod-studio-test


[taxonomies]
  author = "authors"
  tag = "tags"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[outputs]
  home = ["HTML", "RSS", "JSON"]


[markup.highlight]
  codeFences = true
  guessSyntax = true
  noClasses = false
